name: Docker Image scan

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-secure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: docker build -f ./Dockerfile.prod -t reports:${{ github.sha }} .
      
    - uses: Azure/container-scan@v0
      with:
        image-name: reports:${{ github.sha }}
